apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linkme-grafana
  name: linkme-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkmed-grafana
  template:
    metadata:
      labels:
        app: linkme-grafana
    spec:
      containers:
        - image: grafana/grafana:latest
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          name: grafana
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: linkme-grafana
spec:
  selector:
    app: linkme-grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30900
      name: "3000"
  type: NodePort
