db:
  dsn: "root:root@tcp(100.64.1.1:30882)/linkme?charset=utf8mb4&parseTime=True&loc=Local"
redis:
  addr: "100.64.1.1:30884"
  filepath: "logs/linkme.json"
mongodb:
  addr: "mongodb://100.64.1.1:30883"
kafka:
  addr: "100.64.1.1:30880"
es:
  addr: "http://100.64.1.1:30885"
sms:
  tencent:
    secretId: ""
    secretKey: ""
    endPoint: ""
    smsID: ""
    sign: ""
    templateID: ""
